---

sshd_package_name: openssh
sshd_service_name: sshd

sshd_acceptenv:
  - 'lang lc_ctype lc_numeric lc_time lc_collate lc_monetary lc_messages'
  - 'lc_identification lc_all language'
  - 'lc_paper lc_name lc_address lc_telephone lc_measurement'
  - 'xmodifiers'
sshd_gssapiauthentication: 'yes'
sshd_gssapicleanupcredentials: 'no'
sshd_hostkey:
  - /etc/ssh/ssh_host_ecdsa_key
  - /etc/ssh/ssh_host_ed25519_key
  - /etc/ssh/ssh_host_rsa_key
sshd_subsystem_sftp: /usr/libexec/openssh/sftp-server
sshd_syslogfacility: authpriv
sshd_useprivilegeseparation: sandbox
