---

- hosts: all
  become: true
  vars:
    sshd_match_block: |
      Match group ftp
        X11Forwarding no
  roles:
    - {role: sshd, tags: ssh}
    - {role: supervisor, tags: supervisor}
    - {role: vsftpd, tags: ftp}
