---
# playbook to execute all roles on all hosts in inventory

- hosts: all
  become: true
  vars:
    #aws_access_key_id: <aws_access_key_id>
    #aws_secret_access_key: <aws_secret_access_key>
    sshd_match_block: |
      Match group ftp
        X11Forwarding no
  roles:
    #- {role: awslogs, tags: awslogs}
    - {role: sshd, tags: ssh}
    - {role: supervisor, tags: supervisor}
    - {role: vsftpd, tags: ftp}
