---

# shared OS defaults
vsftpd_connect_from_port_20: 'yes'
vsftpd_dirmessage_enable: 'yes'
vsftpd_local_enable: 'yes'
vsftpd_xferlog_enable: 'yes'

# application defaults
#vsftpd_accept_timeout: '60'
#vsftpd_allow_anon_ssl: 'no'
#vsftpd_anon_max_rate: '0'
#vsftpd_anon_mkdir_write_enable: 'no'
#vsftpd_anon_other_write_enable: 'no'
#vsftpd_anon_root: ''
#vsftpd_anon_umask: '077'
#vsftpd_anon_upload_enable: 'no'
#vsftpd_anon_world_readable_only: 'yes'
#vsftpd_anonymous_enable: 'yes'
#vsftpd_ascii_download_enable: 'no'
#vsftpd_ascii_upload_enable: 'no'
#vsftpd_async_abor_enable: 'no'
#vsftpd_background: 'no'
#vsftpd_banned_email_file: '/etc/vsftpd.banned_emails'
#vsftpd_banner_file: ''
#vsftpd_ca_certs_file: ''
#vsftpd_check_shell: 'yes'
#vsftpd_chmod_enable: 'yes'
#vsftpd_chown_upload_mode: '0600'
#vsftpd_chown_uploads: 'no'
#vsftpd_chown_username: 'root'
#vsftpd_chroot_list_enable: 'no'
#vsftpd_chroot_list_file: '/etc/vsftpd.chroot_list'
#vsftpd_chroot_local_user: 'no'
#vsftpd_cmds_allowed: ''
#vsftpd_cmds_denied: ''
#vsftpd_connect_from_port_20: 'no'
#vsftpd_connect_timeout: '60'
#vsftpd_data_connection_timeout: '300'
#vsftpd_debug_ssl: 'no'
#vsftpd_delay_failed_login: '1'
#vsftpd_delay_successful_login: '0'
#vsftpd_delete_failed_uploads: 'no'
#vsftpd_deny_email_enable: 'no'
#vsftpd_deny_file: ''
#vsftpd_dirlist_enable: 'yes'
#vsftpd_dirmessage_enable: 'no'
#vsftpd_download_enable: 'yes'
#vsftpd_dsa_cert_file: ''
#vsftpd_dsa_private_key_file: ''
#vsftpd_dual_log_enable: 'no'
#vsftpd_email_password_file: '/etc/vsftpd.email_passwords'
#vsftpd_file_open_mode: '0666'
#vsftpd_force_anon_data_ssl: 'no'
#vsftpd_force_anon_logins_ssl: 'no'
#vsftpd_force_dot_files: 'no'
#vsftpd_force_local_data_ssl: 'yes'
#vsftpd_force_local_logins_ssl: 'yes'
#vsftpd_ftp_data_port: '20'
#vsftpd_ftpd_banner: ''
#vsftpd_ftp_username: 'ftp'
#vsftpd_guest_enable: 'no'
#vsftpd_guest_username: 'ftp'
#vsftpd_hide_file: ''
#vsftpd_hide_ids: 'no'
#vsftpd_idle_session_timeout: '300'
#vsftpd_implicit_ssl: 'no'
#vsftpd_listen: 'no'
#vsftpd_listen_address6: ''
#vsftpd_listen_address: ''
#vsftpd_listen_ipv6: 'no'
#vsftpd_listen_port: '21'
#vsftpd_local_enable: 'no'
#vsftpd_local_max_rate: '0'
#vsftpd_local_root: ''
#vsftpd_local_umask: '077'
#vsftpd_lock_upload_files: 'yes'
#vsftpd_log_ftp_protocol: 'no'
#vsftpd_ls_recurse_enable: 'no'
#vsftpd_max_clients: '0'
#vsftpd_max_login_fails: '3'
#vsftpd_max_per_ip: '0'
#vsftpd_mdtm_write: 'yes'
#vsftpd_message_file: '.message'
#vsftpd_no_anon_password: 'no'
#vsftpd_no_log_lock: 'no'
#vsftpd_nopriv_user: 'nobody'
#vsftpd_one_process_model: 'no'
#vsftpd_pam_service_name: 'vsftpd'
#vsftpd_passwd_chroot_enable: 'no'
#vsftpd_pasv_address: ''
#vsftpd_pasv_addr_resolve: 'no'
#vsftpd_pasv_enable: 'yes'
#vsftpd_pasv_max_port: '0'
#vsftpd_pasv_min_port: '0'
#vsftpd_pasv_promiscuous: 'no'
#vsftpd_port_enable: 'yes'
#vsftpd_port_promiscuous: 'no'
#vsftpd_require_cert: 'no'
#vsftpd_require_ssl_reuse: 'yes'
#vsftpd_rsa_cert_file: '/usr/share/ssl/certs/vsftpd.pem'
#vsftpd_rsa_private_key_file: ''
#vsftpd_run_as_launching_user: 'no'
#vsftpd_secure_chroot_dir: '/var/run/vsftpd/empty'
#vsftpd_secure_email_list_enable: 'no'
#vsftpd_session_support: 'no'
#vsftpd_setproctitle_enable: 'no'
#vsftpd_ssl_ciphers: 'des-cbc3-sha'
#vsftpd_ssl_enable: 'no'
#vsftpd_ssl_request_cert: 'yes'
#vsftpd_ssl_sslv2: 'no'
#vsftpd_ssl_sslv3: 'no'
#vsftpd_ssl_tlsv1: 'yes'
#vsftpd_strict_ssl_read_eof: 'no'
#vsftpd_strict_ssl_write_shutdown: 'no'
#vsftpd_syslog_enable: 'no'
#vsftpd_tcp_wrappers: 'no'
#vsftpd_text_userdb_names: 'no'
#vsftpd_tilde_user_enable: 'no'
#vsftpd_trans_chunk_size: '0'
#vsftpd_use_localtime: 'no'
#vsftpd_user_config_dir: ''
#vsftpd_userlist_deny: 'yes'
#vsftpd_userlist_enable: 'no'
#vsftpd_userlist_file: '/etc/vsftpd.user_list'
#vsftpd_user_sub_token: ''
#vsftpd_use_sendfile: 'yes'
#vsftpd_validate_cert: 'no'
#vsftpd_virtual_use_local_privs: 'no'
#vsftpd_vsftpd_log_file: '/var/log/vsftpd.log'
#vsftpd_write_enable: 'no'
#vsftpd_xferlog_enable: 'no'
#vsftpd_xferlog_file: '/var/log/xferlog'
#vsftpd_xferlog_std_format: 'no'
