---

- name: install Debian openssh package
  apt:
    name: ssh
    state: latest
  when: ansible_os_family == "Debian"

- name: install RedHat openssh package
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - openssh-server
    - openssh-clients
  when: ansible_os_family == "RedHat"
