---

- name: Install python build dependencies
  apt: name="{{item}}" state=latest update_cache=true
  with_items: "{{python_dependencies}}"

- name: Download python tarball
  get_url: url="{{python_tar_url}}" dest=/tmp/

- name: Unpack python tarball
  unarchive: src="/tmp/{{python_tar_dir}}.tgz" dest=/tmp/ copy=no

- name: Build python
  shell: './configure; make; make install'
  args:
    chdir: "/tmp/{{python_tar_dir}}"
    creates: "/usr/local/bin/{{python_basename}}"

- name: Download get-pip.py
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp/

- name: Install pip
  command: "{{python_basename}} /tmp/get-pip.py"

- name: Install virtualenv
  pip: name=virtualenv state=latest
