---

# Install python
- name: Check if python is already installed
  stat: path="{{python_path}}"
  register: python_installed

- name: Install python
  include: install_python.yml
  when: python_installed.stat.exists == false

# Install/upgrade pip
- name: Check if pip is already installed
  stat: path="{{pip_path}}"
  register: pip_installed

- name: Install pip
  include: install_pip.yml
  when: pip_installed.stat.exists == false

- name: Upgrade pip
  pip: name=pip state=latest executable="{{pip_path}}"

# Install packages
- name: Install/upgrade virtualenv
  pip: name=virtualenv state=latest executable="{{pip_path}}"
  when: python_major_version == '2'

- name: Install global packages
  pip: name="{{item}}" state=present executable="{{pip_path}}"
  with_items: "{{python_global_packages}}"
