---

- name: install python packages
  package:
    name: "{{item}}"
    state: present
  with_items:
    - python
    - python-setuptools

- name: install pip package manager
  easy_install:
    name: pip
    state: present
