---

python_dependencies:
  - build-essential
  - libbz2-dev
  - libdb-dev
  - libgdbm-dev
  - liblzma-dev
  - libncursesw5-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - python-dev
  - tk-dev
  - zlib1g-dev
