---

python_version: ''
python_major_version: "{{python_version[0]}}"
python_tar_dir: "Python-{{python_version}}"
python_tar_url: "https://www.python.org/ftp/python/{{python_version}}/{{python_tar_dir}}.tgz"
python_global_packages:
  - virtualenv
python_dependencies:
  - build-essential
  - libbz2-dev
  - libdb-dev
  - libgdbm-dev
  - liblzma-dev
  - libncurses-dev
  - libreadline-dev
  - libsqlite3-dev
  - libssl-dev
  - python-dev
  - tk-dev
  - zlib1g-dev
