---

- name: Get OS specific vars
  group_by:
    key: "vsftpd_{{ansible_distribution}}{{ansible_distribution_major_version}}"

- name: Install vsftpd package
  package:
    name: vsftpd
    state: present

- name: Update vsftpd.conf
  template:
    src: vsftpd.conf.j2
    dest: "{{ vsftpd_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart vsftpd

- name: Add nologin to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: /usr/sbin/nologin

- name: Ensure vsftpd is enabled and running
  service:
    name: vsftpd
    enabled: yes
    state: running
