---

- name: Get OS specific vars
  group_by:
    key: "sshd_{{ansible_distribution}}{{ansible_distribution_major_version}}"

- name: apt-get update on Ubuntu hosts
  apt: update_cache=yes
  when: ansible_distribution == 'Ubuntu'

- name: install ssh packages
  package:
    name: "{{sshd_package_name}}"
    state: latest

- name: Update sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart sshd

- name: Ensure sshd is enabled and started
  service:
    name: "{{sshd_service_name}}"
    enabled: yes
    state: started
